### ISSUE TITLE
Formulaire bénévoles

### ISSUE THREAD

**Issue by FaXaq** [blank-project/project-belleville-en-vrai#2]
Lister les actions des bénévoles.
Besoin urgent.
Développer le formulaire.
Voir avec Antonin.

**Comment by TotorBelleville** [comment]
- Nom, prénom, email, tel
- Disponibilité : vendredi 10 mai (18h-21h), samedi 20 mai matin et aprem (8h-13h), 13h - 20h, dimanche 21 pareil. 
- taches : encadrement sportif, logistique, photo-vidéo, loges/accueil artistes, catering, accueil/propreté
- taille de t shirt (S, M, L, XL)
- informations complémentaires
